<div id="social-media">
	<ul>
		<li><a href="https://plus.google.com/share?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>" onclick="javascript:void window.open('https://plus.google.com/share?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Google+!"><i class="fa fa-google-plus"></i></a></li>
		<li><a href="http://www.facebook.com/sharer/sharer.php?u=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>" onclick="javascript:void window.open('http://www.facebook.com/sharer/sharer.php?u=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Facebook!"><i class="fa fa-facebook"></i></a></li>
		<li><a href="https://twitter.com/intent/tweet?text=<?php echo esc_attr(get_the_title()); ?>&url=< ?php echo esc_url(get_permalink()); ?>" onclick="javascript:void window.open('https://twitter.com/intent/tweet?text=<?php echo esc_attr(get_the_title()); ?>&url=< ?php echo esc_url(get_permalink()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Twitter!"><i class="fa fa-twitter"></i></a></li>
		<li><a href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>&summary=< ?php echo esc_attr(get_the_title()); ?>&source={< ?php echo esc_url(home_url()); ?>" onclick="javascript:void window.open('http://www.linkedin.com/shareArticle?mini=true&url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>&summary=< ?php echo esc_attr(get_the_title()); ?>&source={< ?php echo esc_url(home_url()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on LinkedIn!"><i class="fa fa-linkedin"></i></a></li>
		<li><a href="http://www.stumbleupon.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?" onclick="javascript:void window.open('http://www.stumbleupon.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on StumbleUpon!"><i class="fa fa-stumbleupon"></i></a></li>
		<li><a href="http://del.icio.us/post?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>" onclick="javascript:void window.open('http://del.icio.us/post?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Delicious!"><i class="fa fa-delicious"></i></a></li>
		<li><a href="http://digg.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>" onclick="javascript:void window.open('http://digg.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Digg!"><i class="fa fa-digg"></i></a></li>
		<li><a href="http://reddit.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>" onclick="javascript:void window.open('http://reddit.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Reddit!"><i class="fa fa-reddit"></i></a></li>
	</ul>
</div>